require "simple_form_extension/inputs/date_time"
require "simple_form_extension/inputs/boolean_input"
require "simple_form_extension/inputs/numeric"
require "simple_form_extension/inputs/collection_check_boxes_input"
require "simple_form_extension/inputs/collection_radio_buttons_input"
require "simple_form_extension/inputs/color"
require "simple_form_extension/inputs/file"
require "simple_form_extension/inputs/image"